name: mrzflutterplugin_example
description: Demonstrates how to use the mrzscanner_flutter plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1
  archive: ^3.1.2
  collection: ^1.16.0
  convert: ^3.0.0
  crypto: ^3.0.1
  expandable: ^5.0.1
  fixnum: ^1.0.0
  flutter_nfc_kit: ^3.3.1
  logging: ^1.0.1
  meta: ^1.3.0
  tripledes_nullsafety: ^1.0.3
  pointycastle: ^3.7.3
  intl: ^0.19.0
  google_mlkit_text_recognition: ^0.4.0
  camera: ^0.10.0+4
  google_mlkit_commons: ^0.2.0
  camera_platform_interface: ^2.2.2

  # mrzscanner_flutter:
    # When depending on this package from a real application you should use:
    #   mrzscanner_flutter: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    # path: lib/mrz_lib

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_logo.jpg"

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app_banner.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
